import { Router } from 'express'; import { verifyToken } from '../../middlewares/auth.js'; import { formSubmitLimiter } from '../../middlewares/rateLimit.js'; import * as ctrl from './commerce.ctrl.js';
const router = Router();
router.get('/products/:projectId', ctrl.products);
router.post('/checkout', formSubmitLimiter, ctrl.checkout);
router.get('/orders/:projectId', verifyToken, ctrl.orders);
router.get('/stripe/status/:projectId', verifyToken, ctrl.stripeStatus);
router.post('/stripe/connect/:projectId', verifyToken, ctrl.stripeConnect);
router.get('/stripe/callback', ctrl.stripeCallback);
router.delete('/stripe/:projectId', verifyToken, ctrl.stripeDisconnect);
export default router;
