import * as Landing from './Landing';

// Keep these keys stable: Craft.js stores component names in serialized projects.
export const editorResolver = {
  Container: Landing.Container,
  Text: Landing.Text,
  Custom1: Landing.Custom1,
  Custom2: Landing.Custom2,
  Custom2VideoDrop: Landing.Custom2VideoDrop,
  Custom3: Landing.Custom3,
  Custom3BtnDrop: Landing.Custom3BtnDrop,
  OnlyButtons: Landing.OnlyButtons,
  Button: Landing.Button,
  Video: Landing.Video,
  YouTube: Landing.YouTube,
  BackgroundVideo: Landing.BackgroundVideo,
  Link: Landing.Link,
  Form: Landing.Form,
  Image: Landing.Image,
  Carousel: Landing.Carousel,
  Map: Landing.Map,
  NavbarElement: Landing.NavbarElement,
  Heading: Landing.Heading,
  Columns: Landing.Columns,
  Spacer: Landing.Spacer,
  Divider: Landing.Divider,
  List: Landing.List,
  Quote: Landing.Quote,
  Icon: Landing.Icon,
  Badge: Landing.Badge,
  Accordion: Landing.Accordion,
  Pricing: Landing.Pricing,
  Testimonial: Landing.Testimonial,
  Stats: Landing.Stats,
  TeamGrid: Landing.TeamGrid,
  Timeline: Landing.Timeline,
  CTABanner: Landing.CTABanner,
  LogoStrip: Landing.LogoStrip,
  SocialLinks: Landing.SocialLinks,
  Newsletter: Landing.Newsletter,
  Booking: Landing.Booking,
  ProductCatalog: Landing.ProductCatalog,
  Engagement: Landing.Engagement,
  Tabs: Landing.Tabs,
  Countdown: Landing.Countdown,
};
